services:
  db:
    image: postgres
    container_name: product-db
    environment:
      POSTGRES_DB: product-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ecommerce_data:/var/lib/postgresql/data
  
  stock-db:
    image: postgres
    container_name: stock-db
    environment:
      POSTGRES_DB: stock-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - stock_data:/var/lib/postgresql/data

  order-db:
    image: postgres
    container_name: order-db
    environment:
      POSTGRES_DB: order-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - order_data:/var/lib/postgresql/data

  customer-db:
    image: postgres
    container_name: customer-db
    environment:
      POSTGRES_DB: customer-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
    volumes:
      - customer_data:/var/lib/postgresql/data
volumes:
  ecommerce_data:
  stock_data:
  order_data:
  customer_data: