spring:
  application:
    name: customer-service
  datasource:
    username: ${DB_STOCK_USERNAME:admin}
    password: ${DB_STOCK_PASSWORD:admin}
    url: jdbc:postgresql://localhost:5435/customer-db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}