services:
  db:
    image: postgres
    container_name: product-db
    environment:
      POSTGRES_DB: product-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ecommerce_data:/var/lib/postgresql
volumes:
  ecommerce_data: